# Configuration Mosquitto pour le développement
# Pas d'authentification (mode allow_anonymous)

listener 1883
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true

persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
